[workspace]
members = [
    "rusty-golf-actix",
    "rusty-golf-core",
    "rusty-golf-serverless", "rusty-golf-setup",
    "rusty-golf-tests",
]
resolver = "3"

[workspace.lints.rust]
unsafe_code = "forbid"
