[package]
name = "rusty-golf-serverless"
version = "0.1.0"
edition = "2024"

[dependencies]
rusty-golf-core = { path = "../rusty-golf-core" }
worker = "0"
async-trait = "0"
chrono = "0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
worker-kv = "0"
