[package]
name = "rusty-golf-core"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0"
ahash = "0"
chrono = "0"
maud = "0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
