[package]
name = "rusty-golf-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
chrono = "0"
scraper = "0"
serde_json = "1"
sql-middleware = "0.4.0"
rusty-golf = { path = "../rusty-golf-actix" }
